name: mlops-exaple-tensorflow-regression
on:
  workflow_dispatch:
    inputs:
      name:
        required: false
        default: "test"
        description: "generate data files from mongodb and analyse data"
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          python model.py
          
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md
          
          echo "\n## Model Performance" >> report.md
          
      - name: Get New Files
        run: |
          git status -uno
          
      - uses: EndBug/add-and-commit@v7
        with:
          add: report.md
          author_name: GithubActions States Update
          author_email: pateldevarsh1206@gmail.com
          message: "Adding files"
